version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-oakcrime-{{ checksum "showCrime/requirements.txt" }}
            - v1-oakcrime-
      - run:
          name: create virtualenv and install dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r showCrime/requirements.dev.txt
            pip install -r showCrime/requirements.txt
      - save_cache:
          key: v1-oakcrime-{{ checksum "showCrime/requirements.txt" }}
          paths:
            - venv
      - run:
          name: lint python files
          command: |
            source venv/bin/activate
            make lint

  ansible-test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-oakcrime-ansible-{{ checksum "ansible/requirements.txt" }}
            - v1-oakcrime-ansible-
      - run:
          name: create virtualenv and install dependencies
          command: |
            virtualenv ansible/venv
            source ansible/venv/bin/activate
            pip install -r ansible/requirements.txt
      - save_cache:
          key: v1-oakcrime-ansible-{{ checksum "ansible/requirements.txt" }}
          paths:
            - ansible/venv
      - run:
          name: make test
          command: |
            cd ansible
            source venv/bin/activate
            make test


workflows:
  version: 2
  commit:
    jobs:
      - build
      - ansible-test
