version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/project/showCrime
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            make docker.pull
            make docker.build
      - run:
          name: Code quality
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "make quality"
      - run:
          name: Migration testing
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "./wait-for-it.sh db:5432 -- make detect_missing_migrations"
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "./wait-for-it.sh db:5432 -- make migrate"
      - run:
          name: Build static files
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "./wait-for-it.sh db:5432 -- make static"
      - run:
          name: Python testing
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "./wait-for-it.sh db:5432 -- make test"

  ansible-test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-oakcrime-ansible-{{ checksum "ansible/requirements.txt" }}
            - v1-oakcrime-ansible-
      - run:
          name: create virtualenv and install dependencies
          command: |
            virtualenv ansible/venv
            source ansible/venv/bin/activate
            pip install -r ansible/requirements.txt
      - save_cache:
          key: v1-oakcrime-ansible-{{ checksum "ansible/requirements.txt" }}
          paths:
            - ansible/venv
      - run:
          name: make test
          command: |
            cd ansible
            source venv/bin/activate
            make test


workflows:
  version: 2
  commit:
    jobs:
      - build
      - ansible-test
