# following https://github.com/technivore/ansible-django
---
- hosts: servers
  vars_files:
    - vars.yml
    - OC-secureVars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Clone/pull project repo
      git: repo={{ project_repo }} dest={{ install_root }}/{{ project_name }} accept_hostkey=yes
      notify:
      - restart apache

    - name: install python packages
      pip: requirements={{ install_root }}/{{ project_name }}/requirements.txt
      notify:
      - restart apache

    # Load the initial_data fixture into the application
    - django_manage:
        command: loaddata
        app_path: "{{ django_dir }}"
        fixtures: "{{ initial_data }}"

    # Run syncdb on the application
    - django_manage:
        command: migrate # syncdb
        app_path: "{{ django_dir }}"
        settings: "{{ settings_app_name }}"
        pythonpath: "{{ settings_dir }}"

    # Run the SmokeTest test case from the main app. Useful for testing deploys.
    - django_manage:
        command: test
        app_path: "{{ django_dir }}"
        apps: main.SmokeTest

    # Create an initial superuser.
    - django_manage:
        command: "createsuperuser --noinput --username=admin --email=admin@example.com"
        app_path: "{{ django_dir }}"

# harvestPatrolLog
- django_manage:
    command: "harvestPatrolLog"
    app_path: "{{ django_dir }}"

    # TODO
    
    - name: establish cron jobs for harvesters, db copying

    - name: backup DB on remote machine
      
    - name: copy apache config

    - name: make sure apache server is running
    
  handlers: 
    - name: restart apache
      service: name=apache state=restarted

